sudo: false
language: python

os: linux
arch: 
  - amd64
  - arm64
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
# Enable 3.7 and 3.8 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - arch: arm64
      python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
    - arch: arm64
      python: 3.8
      dist: xenial
      sudo: true

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      wget https://github.com/Kitware/CMake/releases/download/v3.11.0/cmake-3.11.0.tar.gz;
      tar -xvf cmake-3.11.0.tar.gz;
      cd cmake-3.11.0;
      ./bootstrap;
      make;
      sudo make install;
    fi;
  - pip install -q numpy psutil
  - pip install -r requirements-dev.txt
install:
  - make build

script:
  - make test
